# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 172c8b7875196bf550e42b5464bde3b991224116f361984fb1a17a006f4092ffd0406a09874601c6bb012e21e2b179912def2cf6b38a6e2e517f6f5fd1d01d90

test:
  secret_key_base: 06810fb1f8f809d36f17d7f9ec01520ce984e55e7c540cc31ef8bd9b969c5675f2d2fc379ed45256973744aae63d6df0fcaf0ab4d9dc5c203b7bf803f92296f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
